### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by 212haiyang** [Arrowes/CEAM-YOLOv7#1]
## ❔Question
您好，想跟您咨询一下数据集以及数据集的配置文件

**Comment by Arrowes** [comment]
抱歉，数据集是学校研究用，不允许公开的

**Comment by 212haiyang** [comment]
好的谢谢您，还想跟您咨询一下 代码我detect的时候误检比较高是什么原因呢，选择的是exp5 gam3 Mish0的best.pt进行检测的

**Comment by wyhAndy** [comment]
你好，可以有相关图片用来检测下吗？因为找不到相关红外像的图片进行检测
